name: minichatappmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2

  # HTTP Client
  dio: ^5.4.0

  # State Management
  flutter_bloc: ^8.1.3

  # Local Storage (token, cache user, cache chat)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Realtime Socket.IO
  socket_io_client: ^2.0.3+1

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
