name: minichatappmobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8

  # Local preferences


  # HTTP Client
  dio: ^5.4.0

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.2

  # Local Storage (token, cache user, cache chat)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Realtime Socket.IO
  socket_io_client: ^2.0.3+1
  http: ^1.2.2

  # Utilities
  intl: ^0.19.0

  # QR / Scan
  mobile_scanner: ^7.1.4
  google_sign_in: ^6.2.1

  # Pickers / Open file
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
